name: Check build succeeds with no warnings

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        uv pip install --system -r pyproject.toml

    - name: Build documentation
      run: |
        # We use 'uv run' here to ensure sphinx-build executes inside the correct environment
        uv run sphinx-build -W -b html ./source/ ./build/html
